### ISSUE TITLE
Using latex for mathematical expressions

### ISSUE THREAD

**Issue by astro-ray** [dylannalex/electripy#6]
For the documentation, I think it would be a good idea to use latex for the math expressions instead of HTML. That would make future editing of documentation easier, and you would have more conventional notations for the expressions.

**Comment by dylannalex** [comment]
Hey @ritamsaha00, thanks for opening an Issue. Using Latex for math expressions sounds great!  Would you like to help me with that? You can update [PHYSICS.md](https://github.com/dylannalex/electripy/blob/master/PHYSICS.md) and make a PR.

**_Tip:_**  if you want to work on it, make a single commit with all the changes you make to PHYSICS.md. If you need help with GitHub and/or Git, don't hesitate to ask me.

**Comment by astro-ray** [comment]
> If you need help with GitHub and/or Git, don't hesitate to ask me.

I will gladly take that offer. TBH, I still haven't figured out how to commit multiple file changes in a single commit.

**Comment by dylannalex** [comment]
I'd love to help you. If you want you can send me your phone number to tintenfichdylan05@gmail.com so we can communicate via What's App. I think it's more comfortable and faster for communicating.
